export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api'

export { cartService } from './cartService'
export { userService } from './userService'
export { saleService } from './saleService'
export { reviewService } from './reviewService'
export { notificationService } from './notificationService'
export { storeService } from './storeService'
export { productService } from './productService'
export { authService } from './authService'
